### ISSUE TITLE
3분 모나드 글 fmap2 구현

### ISSUE THREAD

**Issue by 5HARK** [ENvironmentSet/overcurried#1]
https://github.com/ENvironmentSet/overcurried/blob/master/content/posts/3%EB%B6%84%20%EB%AA%A8%EB%82%98%EB%93%9C/index.md

글에서 ```fmap2``` 함수의 구현에 오타가 있는 것 같습니다.

```
function fmap2<A, B, C>(pair: [A, B], f: (b: B) => C): [A, C] {
  return bimap(pair, f, id);
}
```
가 아닌
```
function fmap2<A, B, C>(pair: [A, B], f: (b: B) => C): [A, C] {
  return bimap(pair, id, f);
}
```
인 것 같습니다.

https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABDAJgHgIID4AUBDALkQwEoiNEBvAWAChFEAnAUyhEaTwG46BfOuqEiwEiAEYwAtngAOmADSIAQooDCigCK4A2nkViAukW0ZFSg4uBF85EogC8WROsQBza2KJK7jxBrKI2i4aBlR0DCxsHIHA+CSKrjhiJAY8tPy0guDQ8EjA0nKmymo6euJGgUXmlh5ePk6qASZqoTT0TKzsSLqWSSlpGVnCuYj5sgBMCsXOuDJ4MIzGVRajtcr1zk1Fqq3hHVFIEgU4cwuKqJYkAwK0EAgAzlCjDog2iGAgkmLMjBt4iAAqRDjOh3MD3OAAG2YADpIXBEnsAAZjGQ4bQARkU4xWwACABJKKj0VjgbiSLwkYgSKCHlDYfDEe0UQVxiTseSiITUWzMRzLpTqUA

**Comment by ENvironmentSet** [comment]
감사합니다. [232f393a3c3b984e64daeee0d34dc5a4e9365a14](https://github.com/ENvironmentSet/overcurried/commit/232f393a3c3b984e64daeee0d34dc5a4e9365a14) 에서 수정했습니다 :)
